import {Geist, Geist_Mono, Inter, Roboto} from "next/font/google";
import "./globals.css";
import NavMain from "@/componensts/nav_main";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const inter = Inter({subsets: ['latin']})
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700']
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "App Cepi",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className={`container mx-auto`}>
            <NavMain/>
        </header>
        <main className={`container mx-auto`}>
            {children}
        </main>
        </body>
        </html>
    );
}
